Miner updates
MaynardMiner/SWARM pull request #367
Opened 2021-11-10 02:23 UTC by tmiland

Updated Miners and removed disabled repos.

2021-11-10 02:57 UTC, incodemines requested changes
nvidia-win.json

You missed bminer.
 "version": "16.4.8",
"uri": "https://www.bminercontent.com/releases/bminer-lite-v16.4.8-b37ccb0-amd64.zip"

2021-11-10 04:31 UTC, tmiland commented
> 
> 
> nvidia-win.json
> 
> You missed bminer. "version": "16.4.8", "uri": "https://www.bminercontent.com/releases/bminer-lite-v16.4.8-b37ccb0-amd64.zip"

Updated. 👍

2022-01-09 19:57 UTC, Speeddymon commented
Cryptodredge 0.26.0 is available from the Rainbowminer repository and works well with SWARM so I'd recommend updating the URL instead of deleting the miner:
https://github.com/RainbowMiner/miner-binaries/releases/download/v0.26.0-cryptodredge/CryptoDredge_0.26.0_cuda_11.2_linux.tar.gz

Also there's a typo on amd-win.json in this pull request:
`    "uri": "https://github.com/fancyIX/sgminer-phi2-branch/releases/download/0.7.5-0/sgminer-fancyIX-win64-0.7.5.zip"`
The version line up above is 0.7.6 but the URL here has 0.7.5.

2022-01-09 19:58 UTC, Speeddymon commented on config/update/nvidia-linux.json
> +   "bminer": {
There was an extra space added here that shouldn't be

2022-01-09 19:59 UTC, Speeddymon commented on config/update/amd-win.json
> +    "uri": "https://github.com/fancyIX/sgminer-phi2-branch/releases/download/0.7.5-0/sgminer-fancyIX-win64-0.7.5.zip"
The version here is 0.7.5 but on line 164 it's 0.7.6

2022-04-08 19:46 UTC, merged

2022-04-08 19:46 UTC, MaynardMiner commented
I will add this, but not create a release- It requires me having to make changes for the auto-updater to migrate benchmarks and settings.